FROM docker.io/modularitycontainers/conu

ENV PYTHONDONTWRITEBYTECODE=yes-please

RUN dnf install -y nmap-ncat make && \
    dnf install python2-pytest python3-pytest && \
    pip2 install --user -r ./test-requirements.txt && \
    pip3 install --user -r ./test-requirements.txt
